#!/usr/bin/python
#-*- coding: utf-8 -*-
#
# This is a set of gerrit hooks to interact with trac
# Copyright (C) 2013  Fabian 'xx4h' Melters
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import sys
from optparse import OptionParser

from trac_update import TracGerritTicket

parser = OptionParser()
parser.add_option("-i", "--change", dest="change_id", help="Gerrit change ID")
parser.add_option("-d", "--is-draft", dest="is_draft", help="Gerrit DRAFT")
parser.add_option("-u", "--change-url", dest="change_url", help="GIT Change URL")
parser.add_option("-p", "--project", dest="project_name", help="Gerrit Project Name")
parser.add_option("-b", "--branch", dest="branch_name", help="Gerrit Branch Name")
parser.add_option("-t", "--topic", dest="topic", help="Gerrit topic of Changeset")
parser.add_option("-a", "--author", dest="author", help="Gerrit Comment Author")
parser.add_option("-c", "--commit", dest="commit", help="GIT Commit SHA ID")
parser.add_option("-m", "--comment", dest="comment", help="Gerrit Comment")
parser.add_option("--Code-Review", dest="review", help="Gerrit Review", default=None)

options, args = parser.parse_args()

config_path = '/path/to/your/hooks.config'

# run trac update with hook-name and options
trac_update = TracGerritTicket(hook_name=sys.argv[0],
                               options=options,
                               config_path=config_path)
trac_update.handle_trac()

