#!/usr/bin/python
#-*- coding: utf-8 -*-
#
# This is a set of gerrit hooks to interact with trac
# Copyright (C) 2013  Fabian 'xx4h' Melters
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import sys
from optparse import OptionParser

from trac_update import TracGerritTicket

parser = OptionParser()
parser.add_option("-p", "--project", dest="project_name", help="Gerrit Project Name")
parser.add_option("-r", "--refname", dest="refname", help="Git ref Name")
parser.add_option("-u", "--uploader", dest="uploader", help="Gerrit Uploader")
parser.add_option("-o", "--oldrev", dest="oldrev", help="GIT old rev")
parser.add_option("-n", "--newrev", dest="newrev", help="GIT new rev")

options, args = parser.parse_args()

config_path = '/path/to/your/hooks.config'

trac_update = TracGerritTicket(hook_name=sys.argv[0],
                               options=options,
                               config_path=config_path)
trac_update.check_for_ticket_reference()

